version: '3'
services:
    emilia:
        build: ./emilia
        command: python main.py
        ports: 
            - "8000:8000"
        environment: 
            DB_PASSWORD: password 
    beatrice:
        build: ./beatrice
        command: python main.py
        environment:
            TG_TOKEN: token
        network_mode: host
        depends_on:
            - emilia
